BlogProject.WEBUI/Areas/Administrator/Controllers/PostController.cs
using BlogProject.CORE.Service;
using BlogProject.MODEL.Entities;
using BlogProject.WEBUI.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlogProject.WEBUI.Areas.Administrator.Controllers
{
    [Area("Administrator"), Authorize]
    public class PostController : Controller
    {
        private IHostingEnvironment _hostingEnv;
        private readonly ICoreService<Post> _ps;
        private readonly ICoreService<Category> _cs;

        public PostController(ICoreService<Post> ps, IHostingEnvironment hostingEnv, ICoreService<Category> cs)
        {
            _cs = cs;
            _hostingEnv = hostingEnv;
            this._ps = ps;
        }

        public IActionResult Index()
        {
            return View(_ps.GetAll());
        }

        public IActionResult Insert()
        {
            ViewBag.Categories = new SelectList(_cs.GetActive(), "ID", "CategoryName");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Insert(Post item, List<IFormFile> files)
        {
            ViewBag.Categories = new SelectList(_cs.GetActive(), "ID", "CategoryName");

            item.UserID = Guid.Parse(User.Claims.FirstOrDefault(x => x.Type == "ID").Value);
            item.ViewCount = 0;

            string imgPath = Upload.ImageUpload(files, _hostingEnv, out bool imgResult);
            if (imgResult)
                item.ImagePath = imgPath;
            else
            {
                ViewBag.Message = "Resim yükleme sırasında bir hata oluştu!";
                return View(item);
            }

            if (ModelState.IsValid)
            {
                bool addingResult = _ps.Add(item);

                if (addingResult)
                    return RedirectToAction("Index");
                else
                    ViewBag.Message = "Kayıt işlemi sırasında bir hata oluştu! Lütfen tüm alanları kontrol edip tekrar deneyin!";
            }
            else
                ViewBag.Message = "İşlem başarısız oldu! Lütfen tüm alanları kontrol edin!";
            
            return View(item);
        }

        public IActionResult Activate(Guid id)
        {
            _ps.Activate(id);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(Guid id)
        {
            Post silinecek = _ps.GetByID(id);
            _ps.Remove(silinecek);

            return RedirectToAction("Index");
        }

        public IActionResult Update(Guid id)
        {
            ViewBag.Categories = new SelectList(_cs.GetActive(), "ID", "CategoryName");

            return View(_ps.GetByID(id));
        }

        [HttpPost]
        public async Task<IActionResult> Update(Post item, List<IFormFile> files)
        {
            ViewBag.Categories = new SelectList(_cs.GetActive(), "ID", "CategoryName");

            //item.UserID = Guid.Parse(User.Claims.FirstOrDefault(x => x.Type == "ID").Value);
            Post updated = _ps.GetByID(item.ID);
            updated.Title = item.Title;
            updated.PostDetail = item.PostDetail;
            updated.Tags = item.Tags;

            string imgPath = Upload.ImageUpload(files, _hostingEnv, out bool imgResult);
            if (imgResult)
                updated.ImagePath = imgPath;
            else
            {
                ViewBag.Message = "Resim yükleme sırasında bir hata oluştu!";
                return View(updated);
            }

            if (ModelState.IsValid)
            {
                bool addingResult = _ps.Update(updated);

                if (addingResult)
                    return RedirectToAction("Index");
                else
                    ViewBag.Message = "Kayıt işlemi sırasında bir hata oluştu! Lütfen tüm alanları kontrol edip tekrar deneyin!";
            }
            else
                ViewBag.Message = "İşlem başarısız oldu! Lütfen tüm alanları kontrol edin!";

            return View(updated);
        }
    }
}

BlogProject.WEBUI/Controllers/PostController.cs
using BlogProject.CORE.Service;
using BlogProject.MODEL.Entities;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlogProject.WEBUI.Controllers
{
    public class PostController : Controller
    {
        private readonly ICoreService<Post> _ps;
        private readonly ICoreService<Category> _cs;
        private readonly ICoreService<User> _us;
        private readonly ICoreService<Comment> _cms;

        public PostController(ICoreService<Post> ps, ICoreService<Category> cs, ICoreService<User> us, ICoreService<Comment> cms)
        {
            _ps = ps;
            _cs = cs;
            _cms = cms;
            _us = us;
        }
        public IActionResult Index()
        {
            ViewBag.SonYazilar = _ps.GetActive().OrderByDescending(x => x.CreatedDate).Take(3); // CreatedDate'e göre desc olarak sıralanıp ilk 3 tanesini almak için.
            ViewBag.Kategoriler = _cs.GetActive(); // Kategorileri almıp Index'te sağ alanda göstermek için.
            return View(_ps.GetActive());
        }

        [HttpGet]
        public IActionResult PostDetail(Guid id)
        {
            Post post = _ps.GetByID(id);
            //post.ViewCount++;
            //_ps.Update(post);

            User user = _us.GetByID(post.UserID);
            List<Comment> cmtList = _cms.GetDefault(x => x.Post.ID == post.ID).ToList();
            Category category = _cs.GetByID(post.CategoryID);

            return View(Tuple.Create<Post, User, List<Comment>, Category, Comment>(post, user, cmtList, category, new Comment()));
        }
        [HttpPost]
        public IActionResult AddComment(Comment cmt)
        {
            Comment comment = cmt;
            _cms.Add(comment);

            return RedirectToAction("PostDetail", cmt.PostID);
        }
    }
}

BlogProject.WEBUI/Areas/Administrator/Views/Post/Index.cshtml
@model List<Post>
@{
    ViewData["Title"] = "Index";
}

<div class="row">
    <div class="col-12">
        <a asp-controller="Post" asp-action="Insert" class="btn btn-primary">Yeni Post Ekle</a>
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Makaleler listesini aşağıdaki tabloda bulabilirsiniz.</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <table id="example2" class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>Başlık</th>
                            <th>Etiketler</th>
                            <th>Oluşturulma Tarihi</th>
                            <th>Durumu</th>
                            <th>İşlemler</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Title</td>
                                <td>@item.Tags</td>
                                <td>@item.CreatedDate</td>
                                <td><partial name="PartialViews/_StatusPartial" model="item.Status" /></td>
                                <td>
                                    @*@if (item.Status == Status.Active)
                                        {
                                            <a asp-controller="Post" asp-action="Activate" asp-route-id="@item.ID" class="btn btn-primary btn-sm">Pasifleştir</a>
                                        }
                                        else
                                        {*@
                                    <a asp-controller="Post" asp-action="Activate" asp-route-id="@item.ID" class="btn btn-success btn-sm">Aktif Et</a>
                                    @* } *@


                                    <a asp-controller="Post" asp-action="Update" asp-route-id="@item.ID" class="btn btn-warning btn-sm">Güncelle</a>

                                    <a asp-controller="Post" asp-action="Delete" asp-route-id="@item.ID" class="btn btn-danger btn-sm">Sil</a>
                                </td>
                            </tr>
                        }

                    </tbody>
                    <tfoot>
                        <tr>
                            <th>Başlık</th>
                            <th>Etiketler</th>
                            <th>Oluşturulma Tarihi</th>
                            <th>Durumu</th>
                            <th>İşlemler</th>
                        </tr>
                    </tfoot>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
    <!-- /.col -->
</div>
<!-- /.row -->
<!-- Page specific script -->
@section TabloScript{
    <script>
        $(function () {
            $('#example2').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });
        });
    </script>
}

BlogProject.WEBUI/Areas/Administrator/Views/Post/Insert.cshtml
@model Post
@{
    ViewData["Title"] = "Insert";
}

<!-- Main content -->
<section class="content">
    <div class="row">
        <form asp-controller="Post" asp-action="Insert" method="post" enctype="multipart/form-data">
            <div class="col-md-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Makale Ekle</h3>

                        @*<div class="card-tools">
                                <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                                    <i class="fas fa-minus"></i>
                                </button>
                            </div>*@
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <label asp-for="Title">Makale Başlığı</label>
                            <input type="text" asp-for="Title" class="form-control">
                        </div>
                        <div class="form-group">
                            <label asp-for="PostDetail">İçerik</label>
                            <textarea asp-for="PostDetail" id="summernote" class="form-control" rows="4"></textarea>
                        </div>
                        <div class="form-group">
                            <label asp-for="CategoryID">Kategori</label>
                            <select asp-for="CategoryID" asp-items="@ViewBag.Categories" class="form-control custom-select">
                                <option>Lütfen seçiniz...</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label asp-for="Tags">Etiketler (virgülle ayrılmış)</label>
                            <input type="text" asp-for="Tags" class="form-control">
                        </div>
                        <div class="form-group">
                            <label asp-for="ImagePath">Makale Görseli</label>
                            <div class="input-group">
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input" name="files">
                                    <label class="custom-file-label">Görsel Seç</label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <div class="row">
                <div class="col-12">
                    <input type="submit" value="Makale Ekle" class="btn btn-success btn-block">
                </div>
            </div>
        </form>
    </div>

</section>
<!-- /.content -->
@section summernote{
    <script src="~/admintemplate/plugins/summernote/summernote-bs4.min.js"></script>
}

BlogProject.WEBUI/Areas/Administrator/Views/Post/Update.cshtml
@model Post
@{
    ViewData["Title"] = "Update";
}

<!-- Main content -->
<section class="content">
    <div class="row">
        <form asp-controller="Post" asp-action="Update" method="post" enctype="multipart/form-data">
            <div class="col-md-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Makale Güncelle</h3>

                        @*<div class="card-tools">
                                <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                                    <i class="fas fa-minus"></i>
                                </button>
                            </div>*@
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <label asp-for="Title">Makale Başlığı</label>
                            <input type="text" asp-for="Title" class="form-control">
                        </div>
                        <div class="form-group">
                            <label asp-for="PostDetail">İçerik</label>
                            <textarea asp-for="PostDetail" id="summernote" class="form-control" rows="4"></textarea>
                        </div>
                        <div class="form-group">
                            <label asp-for="CategoryID">Kategori</label>
                            <select asp-for="CategoryID" asp-items="@ViewBag.Categories" class="form-control custom-select">
                                <option>Lütfen seçiniz...</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label asp-for="Tags">Etiketler (virgülle ayrılmış)</label>
                            <input type="text" asp-for="Tags" class="form-control">
                        </div>
                        <div class="form-group">
                            <label asp-for="ImagePath">Makale Görseli</label>
                            <div class="input-group">
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input" name="files">
                                    <label class="custom-file-label">Görsel Seç</label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <div class="row">
                <div class="col-12">
                    <input type="submit" value="Makale Güncelle" class="btn btn-success btn-block">
                </div>
            </div>
        </form>
    </div>

</section>
<!-- /.content -->
@section summernote{
    <script src="~/admintemplate/plugins/summernote/summernote-bs4.min.js"></script>
}